"""schema_update

Revision ID: 07c8b0a23b51
Revises: f0e3545385fc
Create Date: 2021-01-07 23:56:56.117131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c8b0a23b51'
down_revision = 'f0e3545385fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('outflows', sa.Integer(), nullable=False))
    op.drop_column('location', 'outflow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('outflow', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('location', 'outflows')
    # ### end Alembic commands ###
