"""async

Revision ID: 385f610966f1
Revises: 73038b1a03a8
Create Date: 2021-01-06 21:54:19.828386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385f610966f1'
down_revision = '73038b1a03a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
