"""Addign subtitle 

Revision ID: cb0f76f29ab9
Revises: 7b613e505dfc
Create Date: 2021-01-19 14:54:42.635336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0f76f29ab9'
down_revision = '7b613e505dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'subtitle')
    # ### end Alembic commands ###
