"""schema_update

Revision ID: f0e3545385fc
Revises: 5d7c23a0744e
Create Date: 2021-01-07 23:46:57.914772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e3545385fc'
down_revision = '5d7c23a0744e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location', 'dataset',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'dataset',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('flow', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
