"""empty message

Revision ID: fbd0a183f7a7
Revises: 08c12a5738e1
Create Date: 2021-01-19 15:00:41.555275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fbd0a183f7a7"
down_revision = "08c12a5738e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "subtitle", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "subtitle", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
